apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dev-team
  namespace: flux-apps
spec:
  interval: 1m0s
  ref:
    branch: gitopsdays
  timeout: 20s
  url: "https://github.com/lniesz/flux-dev-team"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-team
  namespace: flux-apps
spec:
  serviceAccountName: dev-team
  targetNamespace: flux-apps
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: dev-team
  path: ./clusters/production
  prune: true
  validation: client
